### ISSUE TITLE
Tests fail if ~/.rfc/ does not exist

### ISSUE THREAD

**Issue by jayvdb** [danielmichaels/RFC.py#13]
```
...
[   47s] self = <tests.test_utils.TestUtils testMethod=test_categories>
[   47s] 
[   47s]     def setUp(self):
[   47s]         if not os.path.exists(Config.TESTS_FOLDER):
[   47s] >           os.mkdir(Config.TESTS_FOLDER)
[   47s] E           FileNotFoundError: [Errno 2] No such file or directory: '/home/abuild/.rfc/tests'
[   47s] 
[   47s] tests/test_utils.py:24: FileNotFoundError
```

After manually creating ~/.rfc/ , all tests pass. :+1:

**Comment by danielmichaels** [comment]
Thank you for raising this, and all the other issues - I did not see these until now. They are all valid, and fixable. If you feel the need please raise a PR for this and any other the others.

**Comment by danielmichaels** [comment]
I am closing this, the fix was so simple. Again thank you for raising this issue and apologies for the delayed response.
